services:
  angor:
    image: angor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_FILE_PATH=database/database.json
    ports:
      - "3333:3000"
    volumes:
      - ./database:/app/database
